### PR TITLE
Fix GCC 16 -Werror build failures (satip, ratinglabels)

### LINKED ISSUE #2137: [BUG]: Build fails on GCC 16 due to -Werror (unused-but-set-variable, format-truncation)
### Tvheadend Version
v4.3 (stable)

### Build Number
v4.3-2681-gbb09b4fae

### Platform
Other.. (Fedora 44)

### Architecture
ARMv8 (aarch64)

### Category
Packaging

### Description
Building current master (bb09b4fae) on Fedora 44 with GCC 16.1.1 fails. Two
long-standing constructs are now rejected under the project's default `-Werror`:

1. `src/ratinglabels.c:615` — a local variable that is set but never read:

```
src/ratinglabels.c:615:7: error: variable 'a' set but not used [-Werror=unused-but-set-variable=]
  615 |   int a=1;
      |       ^
```

2. `src/input/mpegts/satip/satip_rtsp.c:364` — `_w[16]` is too small to hold
   `"&tvhweight=%d"` for the full range of `int`:

```
src/input/mpegts/satip/satip_rtsp.c:364:42: error: '%d' directive output may be truncated writing between 1 and 10 bytes into a region of size 5 [-Werror=format-truncation=]
```

Both are dormant (the satip line dates to 2019, the ratinglabels line to 2023);
GCC 16's stricter diagnostics newly promote them to errors.

This isn't caught in CI because the `build-rpm-native` (Fedora) job is marked
`continue-on-error: true`, so its failures don't fail the pipeline.

Fix: #2136

### Reproduction
1. `../configure && make` on Fedora 44 (GCC 16.1.1)
2. Build aborts at `src/ratinglabels.o` / `satip_rtsp.o`.

### PR DESCRIPTION
**Pull request by pimzand**
Current master fails to build on Fedora 44 / GCC 16.1.1 because of two
diagnostics that GCC 16 newly treats as errors under the default `-Werror`.

**satip_rtsp.c** — the fixed 16-byte `_w` buffer cannot hold `"&tvhweight=%d"`
for the full range of `int weight` (worst case 23 bytes incl. NUL), tripping
`-Werror=format-truncation`. Enlarged to 24 bytes.

**ratinglabels.c** — `ratinglabel_class_enabled_notify()` only incremented a
local variable that was never read; it had no observable effect. Removed the
dead body (`-Werror=unused-but-set-variable`), leaving the registered notify
callback as a no-op — no behavior change.

Both are old, dormant lines, not regressions.

Fixes #2137

### CODE REVIEW

**Comment by pimzand** [comment]
Addressed the review feedback on `ratinglabel_class_enabled_notify`: kept it as a registered no-op and added a comment explaining why the body is intentionally empty (toggling `enabled` has no side effect). Left as a separate commit rather than a force-push.

**Comment by pimzand** [comment]
Also, my apologies for how messy this PR became. I was under the impression I should always squash everything into one commit, and at the same time I kept re-running the automated review and reacting to each round of suggestions. Combined, that produced a confusing trail of rewrites and review comments that made the PR much harder to follow than it should have been.

Going forward I'll keep changes as plain follow-up commits so the history stays easy to read. And whenever you're happy with it, I'm glad to do a final squash into a single clean commit at your request — or you can simply squash-merge it yourself.

**Comment by Flole998** [comment]
Its not messy, its a single commit per change just like it should be :) Thanks!
